name = input("What is your name? ")
print("My name is " + name)
where = input("Where do you live? ")
print("I live in " + where)
age = input("How old are you? ")
print("I am " + age)
hobby = input("what is your hobby? ")
print("My hobby is " + hobby)
language = input("what is your language ")
print("My language is " + language)
vacation = input("When is your next vacation ")
print("My next vacation is " + vacation)
